[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-client = "0.2.0"
clap = "4.4.10"
clap_derive = "4.4.2"
dotenv = "0.15.0"
itertools = "0.12.0"
